### ISSUE TITLE
エラーの発生について

### ISSUE THREAD

**Issue by reihac** [RUTE-FSMUSEUM/jre_train_sim_dgo_controller_converter#1]
こんにちは、早速このアプリを試させていただいたのですが、Joystick not found. The sample will now exit.というエラーが出てしまい、起動することが、できませんでした。環境としては、windows 11 pro 64bit、ps1用電車でgoコントローラー、JC-PS101uを使用しています。解決策などがありましたら、ご教授していただければ幸いです。
よろしくお願いいたします。

**Comment by RUTE-FSMUSEUM** [comment]
@RollSignsAssociation さん
こんにちは。フィードバックをありがとうございます。
他の方の環境で果たして動くのか、それが分からなければ私も今後どうしようもないと思っていたので、この度のフィードバックを嬉しく思います。

### なぜエラーが発生するかの仮説
`Joystick not found. The sample will now exit.`のエラーがでるということは、アプリがJC-PS101Uを正しく識別＆接続できなかったということになります。このアプリは、GUIDという識別子を使ってJC-PS101Uを特定しており、そのGUIDは、現状、私が所持しているJC-PS101Uのものを使っています。そして、（おそらく）私が所持しているJC-PS101UのGUIDと、RollSignsAssociationさんが所持しているJC-PS101UのGUIDが違っているために、アプリで指定されているGUIDに一致するコントローラがない＝エラー発生となっているのだと思います。
（そして、細かいことを言うと、私自身もまだ、GUIDの細かい規則性などを理解してないのです...）

### 解決方法

1. RollSignsAssociationさんが所持しているJC-PS101UのGUIDを探していただき、ソースコードのGUID指定部分を書き換えていただく
2. コントローラをドロップダウンなどでリストアップして、アプリと接続したいコントローラを１つ選択できるような機能を追加する
3. GUIDの指定をしないプログラムをアップロードする（非常に暫定的ですが...）

となります。
1. のために、ソースコードをこのあとアップロードしてみます。さらに、GUIDの調査方法と、GUID指定部分の書き換え方法についてもご説明いたしますので、ご自身でご対応いただけますと、直ちにアプリを使用できると思います（ほかに問題がなければですが）。
2. をご希望の場合は、少々お時間をいただくかもしれません。1と3をご希望の場合でも、こちらに取り組みたいと思います。
3. をご希望の場合は、私がGUID指定部分のコードを消して、アプリを再度ビルドすればよいだけなので、比較的はやく問題解決するとは思います。ただし弊害ですが、JC-PS101U**以外**のコントローラ（例えば、ハンドルコントローラーやXboxのコントローラなど）をUSBハブからすべて取り外していただくことになります（さもなくば、関係ないコントローラーとアプリが通信してまい、目的（トレインシムを電車でGOコントローラでプレイするという）が達成されないと思います）

1~3でご希望の対処法がありましたら、返信でお知らせいただけますと幸いです。優先して対応いたします。
また、わたくしも趣味の一環として行っているので、急ぐと言っても、かなりのお時間をいただく可能性があることを予めご了承ください。
以上、今後ともどうぞよろしくお願いします！

**Comment by reihac** [comment]
RUTE-FSMUSEUMさん

お忙しい中お返事ありがとうございます。

解決策に関してですが、
３のGUIDの指定をしないプログラムをアップロードする
でお願いしたいと思います。（トレインシムプレイ中に他のコントローラーを同時に使用することは考えずらいため）

おそらく、JR Train simulator 公式で正式版でのコントローラーサポートは告知されていますが、PS1のコントローラーは切り捨てられてしまうと思います。そのため本当にこのアプリを開発してくださって、感謝しております。
お時間のある時で構いませんので、再ビルドしたものをUPしていただければ嬉しく思います。
こちらこそ、今後ともよろしくお願いします。

**Comment by RUTE-FSMUSEUM** [comment]
@RollSignsAssociation さん

早速にご返信いただき、ありがとうございます。

> おそらく、JR Train simulator 公式で正式版でのコントローラーサポートは告知されていますが、PS1のコントローラーは切り捨てられてしまうと思います。そのため本当にこのアプリを開発してくださって、感謝しております。
お時間のある時で構いませんので、再ビルドしたものをUPしていただければ嬉しく思います。

とんでもないことでございます！
それでは、3. のGUIDの指定をしないプログラムを再度ビルドいたしましたので、共有いたします。

[DgoConverter.noGUID.0.3.4.zip](https://github.com/RUTE-FSMUSEUM/jre_train_sim_dgo_controller_converter/files/9746378/DgoConverter.noGUID.0.3.4.zip)

他のコントローラーを外していただくという、暫定的な対応ですが、こちらで動けば幸いです。

ただし、以下のようなアップデートが入っています。
- ツーハンドル（八高線用）のキーマッピングにも対応しました（上側のドロップダウンから`JRE SIM TWO HANDLE`を選んでください）
- デフォルトではワンハンドル（京浜東北線用）のキーマッピングになっています
- BおよびCボタンに警笛が割り当たっています
- Hmmsim Metroという別のSteamの電車ゲームにも対応しています（バグなどはあるかも知れません）

以上のような状況ですので、暫定最新版でご不明な点がありましたらご相談ください。

また、こちらのバージョンでも同様のエラー、その他のエラーが発生しましたら、ご連絡いただければ幸いです。
どうぞよろしくお願いします。

**Comment by reihac** [comment]
@RUTE-FSMUSEUM さん

お忙しい中ビルドしていただきありがとうございます！
今日、私の環境でも無事、動作が確認できました。本当にありがとうございます。

バグなどの報告ですが、

・京浜東北線にて使用したところ、加速5が認識されておらず、コントローラーのほうで、最大限までノッチを入れてもアプリでは加速4と認識されてしまいます。
<img width="216" alt="スクリーンショット 2022-10-11 172234" src="https://user-images.githubusercontent.com/88885244/195038515-985a08d5-80e7-474e-970c-591082de8161.png">
ノッチ４の場合

<img width="216" alt="スクリーンショット 2022-10-11 172255" src="https://user-images.githubusercontent.com/88885244/195038535-266e09df-5f94-4e54-b889-3655b07f3e25.png">
ノッチ５の場合

・コントローラーを比較的素早く動かすと、（アプリがコントローラーの状態を認識する回数が足りないためか）コントローラーとは全く別のノッチが入ったりしてしまいます。

この二点になります。（Hmmsim Metro とツーハンドルコントローラーは私が所持していないため、検証はできませんでした。申し訳ないです。）

この度は本当にありがとうございました。

**Comment by RUTE-FSMUSEUM** [comment]
@RollSignsAssociation さん、ご確認ありがとうございます！
無事動いて良かったです！

それでは、v0.3.4あたりを暫定Releaseにしておきたいと思います。

動作確認もありがとうございます。自分の環境だと、P5のときのX Axisは-24なのですが、RollSignsAssociationさんの環境では-8になるのですね。（自分にはRotationの表記がないのも気になります...）
<img src="https://user-images.githubusercontent.com/63990380/195093836-f32bd732-1cda-4ffb-9383-6e8e9e67d32c.png" width="256">

なりより写真の添付がわかりやすく、以下のアップデートでおそらく対応できたと思います、ご丁寧にありがとうございます。ただし、同様の環境で、デバッグできていないため、もし何か問題があればご連絡ください。
[DgoConverter.noGUID.0.3.5.zip](https://github.com/RUTE-FSMUSEUM/jre_train_sim_dgo_controller_converter/files/9755998/DgoConverter.noGUID.0.3.5.zip)

また、2点目については、読み取り頻度を上げることは可能ですが、良い値の吟味ができていないため、現状、READMEに記載の方法で対処いただいく形です。ご理解いただけますと幸いです。

> この二点になります。（Hmmsim Metro とツーハンドルコントローラーは私が所持していないため、検証はできませんでした。申し訳ないです。）

とんでもありません、こちらこそ、ご丁寧な報告に感謝します。

以上、どうぞよろしくお願いします。

**Comment by reihac** [comment]
@RUTE-FSMUSEUM  さん

返信遅れてしまい申し訳ありません。
再ビルドしていただいたアプリですが、P5を認識することができました。
この度は本当にありがとうございました！

**Comment by RUTE-FSMUSEUM** [comment]
@RollSignsAssociation さん

こちらこそ大幅に返信が遅れまして申し訳ありません。
ご確認ありがとうございました。動作して良かったです！
それでは、v0.3.5を暫定リリースとしたいと思います。
また、認識速度の件は、今後ぜひ取り組みたいと思います。

今後ともよろしくお願いします。
